#!/usr/bin/perl
#require "htmlutilities.lib";
#require "event-common.lib";

print "Content-type: text/html\n\n";

#===========================================
#From eventcommon.lib
#Common values
@months = ("August","September", "October", "November", "December", "January", "February", "March", "April", "May", "June","July","August");
@days = ("Mon", "Tues", "Weds", "Thurs", "Fri", "Sat", "Sun");

$Title = "fachtnaroe.com Shared Calendar";
$imagepath = "/images/";
$bgimagename = "calendar-bg-01.jpg";
$eventdirectory = "20056/";
$pop3server = 'localhost';
$authfile='event-authorised.txt';
$error = undef;
$extension = ".EVT";
$eventversion = "1.2";
$eventsystem = "Event List Generator";
$itemmarker = "<ITEM>";
$itemseparator = "<HR>";
#===========================================

print "<HEAD>$Title</HEAD>";

# These values should be changed manually each year.
$yearstart=2005;
$yearend=2006;
$thisyear=$yearstart;
# The first of August falls on a Monday so daycount starts at 0
$daycount = 0;

foreach $onemonth (@months)
{
 $months{$onemonth}= "31";
}
$months{"September"} = "30";
$months{"April"} = "30";
$months{"June"} = "30";
$months{"November"} = "30";

# Try to sort out leap years. I think there's a rule about 1000's as well...
if ( (($yearend % 4) == 0) && (($yearend % 400) != 0) )
{
 $months{"February"} = 29;
}
else
{
 $months{"February"} = 28;
}

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
$year = $year+1900;
$mon++;
if ($mon < 10) {
 $mon = "0".$mon; }
if ($mday < 10) {
 $mday = "0".$mday; i}
$todayis = $year.$mon.$mday;

&CommonTitle;

#&CommonBody;


print "<div id=\"content\"><center><h1>Calendar $yearstart-$yearend</h1>";
print "<table border=\"1\" width=\"85%\">";
$monthcount = 8;
foreach $onemonth (@months)
{
 print ("<tr><td colspan=\"4\" valign=\"center\"><a name=\"$onemonth\"><b>$onemonth</b></a></td></tr>");
 if ($monthcount > 12) {
  $monthcount = 1; 
  $thisyear = $yearend;
 }
 $monthcode = $monthcount;
 if ($monthcode < 10) {
  $monthcode = "0".$monthcode; }
 $monthcount++;
 for ($day=1; $day <= @months{$onemonth}; $day++)
 {
  $today = $daycount % 7;
  $daycount++;
  if ($day < 10) {
   $filename = $monthcode."0".$day;
  }
  else {
   $filename = "$monthcode$day";
  }
  $filename = $thisyear.$filename;
  $fulldate = $filename;
  $filename = $eventdirectory.$filename.$extension;
  if (($today == 6) || ($today == 5) ) 
  {
   print ("<tr bgcolor=\"#0775bf\">"); 
   print ("<td align=\"center\" valign=\"center\" width=\"5%\" color=\"#ffffff\"><b>$day</b></td>");
   print ("<td align=\"left\" valign=\"center\" width=\"5%\"><i>$days[$today]</i></td>");
   print ("<td valign=\"center\" color=\"#ffffff\">");
  }
  else 
  {
   print ("<tr>");
   print ("<td align=\"center\" width=\"5%\"><font color=\"#000000\"><b>$day</b></font></td>");
   print ("<td align=\"left\" valign=\"center\" width=\"5%\"><font color=\"#000000\">$days[$today]</font></td>");
   print ("<td valign=\"center\"><font color=\"#000000\">"); 
  }
  if ($fulldate eq $todayis) {
   print "<a name=\"today\"></a>"; }
  print "$filename";
  if (-e $filename)
  {
   open (EVENTFILE, "< $filename");
   @eventdetail = <EVENTFILE>;
   close (EVENTFILE);
   $linecount = 1;
   $itemcount = 0;
   foreach $line (@eventdetail)
   {
    if ( (index $line, $itemmarker) > -1) {
    if ($itemcount > 0)
    {
     print $itemseparator; 
    } 
   }
    else
    {
     print "$line"; }
     $linecount++;
     $itemcount++;
   }
  }
  else
  {
   print "&nbsp";
  }
  print <<CELLEND;
</font></td><td width="5%" align="center" valign="center"><small>
<a href=\"event-modify.pl?&filename=$filename&month=$onemonth&day=$day&dow=$days[$today]&returnto=$onemonth\">
<font face="verdana">Modify</a></small></td></tr>
CELLEND
 }
}
print "</table>";
&PrintVersion;


#=======================================
# These routines brought in from the libraries
sub BackButton { print "<P>Please use the back button on your browser to go back and provide the required data."; }

sub RedColor { print "<FONT COLOR=RED>"; }

sub BlackColor { print "<FONT COLOR=BLACK>"; }

sub Bold { print "<B>"; }

sub NoBold { print "</B>"; }

sub BigText { print "<BIG>"; }

sub NoBigText { print "</BIG>"; }

sub ContentType { print "Content-type: text/html\n\n"; }

sub CommonTitle {
 print "<HEAD><TITLE>$Title</TITLE>
<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/style.css\" />
	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /></HEAD>";
}

sub CommonBody {
 print "<BODY BACKGROUND=\"$imagepath$bgimagename\">";
}

sub ReadAuthList {
 open (AUTHFILE, "< $authfile");
 @_ = <AUTHFILE>;
 close (AUTHFILE);
 return @_;
}

sub PrintVersion {
 print "<SMALL><SMALL><h3>Generated By $eventsystem Version $eventversion</SMALL></SMALL><BR>&copy; Fachtna Roe 2003-6</h3>";
}