
function planetsMakeFileNames (path, filename, filetype, min, max) {
    var localArray=[];
    for (var i = min; i<=max; i++ ) {
        planetFilename = path + "/" + filename + i + "." + filetype;
        console.log(planetFilename);
        localArray.push(planetFilename);
    }
    return localArray;
}



//     var redPlanet = ['images/redFrames/redFrame1.png','images/redFrames/redFrame2.png','images/redFrames/redFrame3.png','images/redFrames/redFrame4.png','images/redFrames/redFrame5.png','images/redFrames/redFrame6.png','images/redFrames/redFrame7.png','images/redFrames/redFrame8.png','images/redFrames/redFrame9.png','images/redFrames/redFrame10.png','images/redFrames/redFrame11.png','images/redFrames/redFrame12.png','images/redFrames/redFrame13.png','images/redFrames/redFrame14.png','images/redFrames/redFrame15.png','images/redFrames/redFrame16.png','images/redFrames/redFrame17.png','images/redFrames/redFrame18.png','images/redFrames/redFrame19.png','images/redFrames/redFrame20.png','images/redFrames/redFrame21.png','images/redFrames/redFrame22.png','images/redFrames/redFrame23.png','images/redFrames/redFrame24.png','images/redFrames/redFrame25.png','images/redFrames/redFrame26.png','images/redFrames/redFrame27.png','images/redFrames/redFrame28.png','images/redFrames/redFrame29.png','images/redFrames/redFrame30.png','images/redFrames/redFrame31.png','images/redFrames/redFrame32.png','images/redFrames/redFrame33.png','images/redFrames/redFrame34.png','images/redFrames/redFrame35.png'];
// 	var bluePlanet = ['images/blueFrames/blueFrame1.png','images/blueFrames/blueFrame2.png','images/blueFrames/blueFrame3.png','images/blueFrames/blueFrame4.png','images/blueFrames/blueFrame5.png','images/blueFrames/blueFrame6.png','images/blueFrames/blueFrame7.png','images/blueFrames/blueFrame8.png','images/blueFrames/blueFrame9.png','images/blueFrames/blueFrame10.png','images/blueFrames/blueFrame11.png','images/blueFrames/blueFrame12.png','images/blueFrames/blueFrame13.png','images/blueFrames/blueFrame14.png','images/blueFrames/blueFrame15.png','images/blueFrames/blueFrame16.png','images/blueFrames/blueFrame17.png','images/blueFrames/blueFrame18.png','images/blueFrames/blueFrame19.png','images/blueFrames/blueFrame20.png','images/blueFrames/blueFrame21.png','images/blueFrames/blueFrame22.png','images/blueFrames/blueFrame23.png','images/blueFrames/blueFrame24.png','images/blueFrames/blueFrame25.png','images/blueFrames/blueFrame26.png','images/blueFrames/blueFrame27.png','images/blueFrames/blueFrame28.png','images/blueFrames/blueFrame29.png','images/blueFrames/blueFrame30.png','images/blueFrames/blueFrame31.png','images/blueFrames/blueFrame32.png','images/blueFrames/blueFrame33.png','images/blueFrames/blueFrame34.png','images/blueFrames/blueFrame35.png','images/blueFrames/blueFrame36.png','images/blueFrames/blueFrame37.png','images/blueFrames/blueFrame38.png','images/blueFrames/blueFrame39.png','images/blueFrames/blueFrame40.png','images/blueFrames/blueFrame41.png','images/blueFrames/blueFrame42.png','images/blueFrames/blueFrame43.png'];
// 	var blackPlanet = ['images/blackFrames/blackFrame1.png','images/blackFrames/blackFrame2.png','images/blackFrames/blackFrame3.png','images/blackFrames/blackFrame4.png','images/blackFrames/blackFrame5.png','images/blackFrames/blackFrame6.png','images/blackFrames/blackFrame7.png','images/blackFrames/blackFrame8.png','images/blackFrames/blackFrame9.png','images/blackFrames/blackFrame10.png','images/blackFrames/blackFrame11.png','images/blackFrames/blackFrame12.png','images/blackFrames/blackFrame13.png','images/blackFrames/blackFrame14.png','images/blackFrames/blackFrame15.png','images/blackFrames/blackFrame16.png','images/blackFrames/blackFrame17.png','images/blackFrames/blackFrame18.png','images/blackFrames/blackFrame19.png','images/blackFrames/blackFrame20.png','images/blackFrames/blackFrame21.png','images/blackFrames/blackFrame22.png','images/blackFrames/blackFrame23.png','images/blackFrames/blackFrame24.png','images/blackFrames/blackFrame25.png','images/blackFrames/blackFrame26.png','images/blackFrames/blackFrame27.png','images/blackFrames/blackFrame28.png','images/blackFrames/blackFrame29.png','images/blackFrames/blackFrame30.png','images/blackFrames/blackFrame31.png','images/blackFrames/blackFrame32.png','images/blackFrames/blackFrame33.png','images/blackFrames/blackFrame34.png','images/blackFrames/blackFrame35.png','images/blackFrames/blackFrame36.png','images/blackFrames/blackFrame37.png','images/blackFrames/blackFrame38.png','images/blackFrames/blackFrame39.png','images/blackFrames/blackFrame40.png','images/blackFrames/blackFrame41.png','images/blackFrames/blackFrame42.png','images/blackFrames/blackFrame43.png','images/blackFrames/blackFrame44.png','images/blackFrames/blackFrame45.png','images/blackFrames/blackFrame46.png','images/blackFrames/blackFrame47.png'];
// 	var gasGiant = ['images/gasGiantFrames/gasGiantFrame1.png','images/gasGiantFrames/gasGiantFrame2.png','images/gasGiantFrames/gasGiantFrame3.png','images/gasGiantFrames/gasGiantFrame4.png','images/gasGiantFrames/gasGiantFrame5.png','images/gasGiantFrames/gasGiantFrame6.png','images/gasGiantFrames/gasGiantFrame7.png','images/gasGiantFrames/gasGiantFrame8.png','images/gasGiantFrames/gasGiantFrame9.png','images/gasGiantFrames/gasGiantFrame10.png','images/gasGiantFrames/gasGiantFrame11.png','images/gasGiantFrames/gasGiantFrame12.png','images/gasGiantFrames/gasGiantFrame13.png','images/gasGiantFrames/gasGiantFrame14.png','images/gasGiantFrames/gasGiantFrame15.png','images/gasGiantFrames/gasGiantFrame16.png','images/gasGiantFrames/gasGiantFrame17.png','images/gasGiantFrames/gasGiantFrame18.png','images/gasGiantFrames/gasGiantFrame19.png','images/gasGiantFrames/gasGiantFrame20.png','images/gasGiantFrames/gasGiantFrame21.png','images/gasGiantFrames/gasGiantFrame22.png','images/gasGiantFrames/gasGiantFrame23.png','images/gasGiantFrames/gasGiantFrame24.png','images/gasGiantFrames/gasGiantFrame25.png'];
// 	var greenPlanet = ['images/greenFrames/greenFrame1.png','images/greenFrames/greenFrame2.png','images/greenFrames/greenFrame3.png','images/greenFrames/greenFrame4.png','images/greenFrames/greenFrame5.png','images/greenFrames/greenFrame6.png','images/greenFrames/greenFrame7.png','images/greenFrames/greenFrame8.png','images/greenFrames/greenFrame9.png','images/greenFrames/greenFrame10.png','images/greenFrames/greenFrame11.png','images/greenFrames/greenFrame12.png','images/greenFrames/greenFrame13.png','images/greenFrames/greenFrame14.png','images/greenFrames/greenFrame15.png','images/greenFrames/greenFrame16.png','images/greenFrames/greenFrame17.png','images/greenFrames/greenFrame18.png','images/greenFrames/greenFrame19.png','images/greenFrames/greenFrame20.png','images/greenFrames/greenFrame21.png','images/greenFrames/greenFrame22.png','images/greenFrames/greenFrame23.png','images/greenFrames/greenFrame24.png','images/greenFrames/greenFrame25.png','images/greenFrames/greenFrame26.png','images/greenFrames/greenFrame27.png'];
// 	var lavaPlanet = ['images/lavaFrames/lavaFrame1.png','images/lavaFrames/lavaFrame2.png','images/lavaFrames/lavaFrame3.png','images/lavaFrames/lavaFrame4.png','images/lavaFrames/lavaFrame5.png','images/lavaFrames/lavaFrame6.png','images/lavaFrames/lavaFrame7.png','images/lavaFrames/lavaFrame8.png','images/lavaFrames/lavaFrame9.png','images/lavaFrames/lavaFrame10.png','images/lavaFrames/lavaFrame11.png','images/lavaFrames/lavaFrame12.png','images/lavaFrames/lavaFrame13.png','images/lavaFrames/lavaFrame14.png','images/lavaFrames/lavaFrame15.png','images/lavaFrames/lavaFrame16.png','images/lavaFrames/lavaFrame17.png','images/lavaFrames/lavaFrame18.png','images/lavaFrames/lavaFrame19.png','images/lavaFrames/lavaFrame20.png','images/lavaFrames/lavaFrame21.png','images/lavaFrames/lavaFrame22.png','images/lavaFrames/lavaFrame23.png','images/lavaFrames/lavaFrame24.png','images/lavaFrames/lavaFrame25.png','images/lavaFrames/lavaFrame26.png','images/lavaFrames/lavaFrame27.png','images/lavaFrames/lavaFrame28.png','images/lavaFrames/lavaFrame29.png','images/lavaFrames/lavaFrame30.png','images/lavaFrames/lavaFrame31.png','images/lavaFrames/lavaFrame32.png','images/lavaFrames/lavaFrame33.png','images/lavaFrames/lavaFrame34.png','images/lavaFrames/lavaFrame35.png'];
